{
  profile: user{
    firstName
    lastName
    login
    avatar:avatarUrl
    email
  }
  succeeded: result_aggregate(
    where: {grade: {_gte: 1}, event: {object: {name: {_eq: "${event}"}}}}
  ) {
    aggregate {
      count
    }
  }
  succeededProjects: result(
    where: {grade: {_gte: 1}, event: {object: {name: {_eq: "${event}"}}}}
  ) {
    object {
      name
    }
  }
  failed: result_aggregate(
    where: {grade: {_lt: 1}, event: {object: {name: {_eq: "${event}"}}}}
  ) {
    aggregate {
      count
    }
  }
  failedProjects: result(
    where: {grade: {_lt: 1}, event: {object: {name: {_eq: "${event}"}}}}
  ) {
    object {
      name
    }
  }
  groups :user {
        groups(where: {event: {object: {name: {_eq: "${event}"}}}}) {
          group {
            members {
              user {
                avatarUrl
                login
              }
            }
          }
        }
      }
  xpPerProject: user {
    projects: transactions(
      where: {type: {_eq: "xp"}, originEvent: {object: {name: {_eq: "${event}"}}}}
    ) {
      project: object {
        name
      }
      xp: amount
    }
  }
  auditData: user {
    auditRatio
    totalUp
    totalDown
    totalUpBonus
  }
  
}